### ISSUE TITLE
Auto completion of hvp activities fails if student doesnt meet the minimum grade

### ISSUE THREAD

**Issue by barry-matthias** [davosmith/moodle-checklist#86] opened 2021-09-29 15:41 UTC
Scenario 1

hvp interactive video content with a passing grade and a completion condition of "Student must receive a grade to complete" will not be marked as completed in the checklist module  if the student doesn't achieve the passing grade

The checklist entry for the hvp activity is not marked as completed but the moodle activity completion report does mark it completed but not meeting a passing grade.

Scenario 2
Same as above but if the student does meet the passing grade and as a result the checklist marks the activity as completed as does the activity completion report.

current workaround is too set the passing grade to 0 so any grade meets the minimum grade and the checklist is updated.

LMS version Moodle 3.10.3 (Build: 20210325)
checklist version is 2020111400
hvp version is 2020080400

php version is 7.2
db is Mysql 5.0.12

**Comment by davosmith** [comment] 2021-09-29 16:17
The checklist detects items that are marked as 'complete' or 'complete pass'.

If an item is 'incomplete' or 'complete fail' then the checklist will not update tick it.

This is not specific to the mod_hvp activity and is by design.

If you feel that mod_hvp is incorrectly setting the activity status to 'complete fail', then please contact the developers of that plugin to resolve the issue.

**Closed by davosmith** 2021-09-29 16:17 UTC
